### PR TITLE
fix issue #125

### PR DESCRIPTION
**Pull request by jsyt**
first commit replace `c[j] = (c[j] + b) % 10; ` with `c[j] = b;` in big.js line 848 
second commit add comment `/* big.js v5.2.2 https://github.com/MikeMcl/big.js/LICENCE */` in big.min.js

### CODE REVIEW

**Comment by MikeMcl** [comment]
Thanks for your input.

**Comment by dkent600** [comment]
Wondering why no red=>green test case was included here

**Comment by MikeMcl** [comment]
@dkent600 

This wasn't a bug, just a minor optimisation.

**Comment by dkent600** [comment]
OK, as long as the case being optimized is running green somewhere  :-)

**Pull request merged**
