### PR TITLE
use pkg.files replace npmignore

### PR DESCRIPTION
**Pull request by popomore**
I don't why it doesn't work for npmignore, but pkg.files is better than .npmignore.

### CODE REVIEW

**Comment by popomore** [comment]
```
PATH          SIZE      %   
package.json  835 B     2%  
LICENCE       1.09 kB   2%  
big.min.js    6.1 kB    14% 
README.md     7.58 kB   17% 
big.js        28.71 kB  65% 
                            
DIR           SIZE      %   
.             44.32 kB  100%

PKGFILES SUMMARY
Size on Disk with Dependencies  ~5.66 MB 
Size with Dependencies          ~5.51 MB 
Publishable Size                ~44.32 kB
Number of Directories           1        
Number of Files                 5    
```

**Comment by fengmk2** [comment]
+1

**Comment by MikeMcl** [comment]
Thanks.
Sad that npmignore hasn't ever worked reliably.

**Comment by popomore** [comment]
Can you release a new version?

**Comment by MikeMcl** [comment]
Yes, it's done.

**Comment by popomore** [comment]
:+1:

**Comment by popomore** [comment]
Yes, do you need another PR?

**Comment by nycdotnet** [comment]
Hi - npm isn't just used for Node.  Including the "official" minified file in the package is useful.

**Pull request merged**
